### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an index

### ISSUE THREAD

**Issue by michal-pikusa** [deborausujono/word2vecpy#2]
Hi, I tried running your code, and got this error message:

Reading word 11690000
Unknown vocab size: 68558
Total words in training file: 11690125
Total bytes in training file: 85775698
Vocab size: 45151
Initializing unigram table
Traceback (most recent call last):
  File "word2vec.py", line 388, in <module>
    args.min_count, args.num_processes, bool(args.binary))
  File "word2vec.py", line 354, in train
    table = UnigramTable(vocab)
  File "word2vec.py", line 175, in \_\_init\_\_
    table = np.zeros(table_size, dtype=np.uint32)
TypeError: 'float' object cannot be interpreted as an index`

I can't figure out how to fix it. Could you look into it? Thanks.

**Comment by bughunter99** [comment]
Hi, using below : table_size = **np.uint32**(1e8) # Length of the unigram table

**Comment by michal-pikusa** [comment]
Thanks a lot. Now it's working.
